spring:
  profiles:
    active: dev0
  cloud:
    config:
      override-none: true
---
spring:
  profiles: dev0
  application:
    name: item-service
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://176.61.3.216:2001/eureka,http://176.61.3.216:2002/eureka
---
spring:
  profiles: dev1
  application:
    name: item-service
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://176.61.3.216:2001/eureka,http://176.61.3.216:2002/eureka