spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 176.61.3.217
    port: 5672
    username: admin
    password: admin
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://176.61.3.216:2001/eureka,http://176.61.3.216:2002/eureka
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"